FROM python:3.11-slim

WORKDIR /app

COPY requirements_ui.txt .
RUN pip install --no-cache-dir -r requirements_ui.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "inference/streamlit.py", "--server.address=0.0.0.0", "--server.port=8501"]
